#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flask', 'flask.json']

package_data = \
{'': ['*'], 'flask': ['sansio/*']}

package_dir = \
{'': 'src'}

install_requires = \
['Werkzeug>=2.3.7',
 'Jinja2>=3.1.2',
 'itsdangerous>=2.1.2',
 'click>=8.1.3',
 'blinker>=1.6.2']

extras_require = \
{":python_version < '3.10'": ['importlib-metadata>=3.6.0'],
 'async': ['asgiref>=3.2'],
 'dotenv': ['python-dotenv']}

entry_points = \
{'console_scripts': ['flask = flask.cli:main']}

setup(name='Flask',
      version='3.0.0.dev0',
      description='A simple framework for building complex web applications.',
      author=None,
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.8',
     )
